language: java
jdk: oraclejdk8
env:
  - GRADLE_OPTS="-Dorg.gradle.daemon=false"
before_install:
  - chmod a+x gradlew
  - ./gradlew clean
install: "./gradlew setupCIWorkspace"
script: "./gradlew build"
after_success:
  - ./gradlew githubRelease
#  - ./gradlew bintrayUpload
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false